import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { UserButton } from "@clerk/nextjs";
import Image from "next/image";
import logo from "./logo.png";

const json = require("../package.json");

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <main className="flex min-h-screen flex-col">
            <header className="flex items-center justify-between w-full h-16 px-8">
              <div className="flex items-center space-x-4 -ml-2">
                <Image src={logo} width={40} height={40} alt={"logo"} />
                <h1 className="text-2xl mt-4">Admin Console</h1>
                <p className="text-sm text-gray-700 justify-end">
                  {json.version}
                </p>
              </div>
              <UserButton />
            </header>
            <section>{children}</section>
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
