app = "differential-core"
primary_region = "lax"

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[http_service.concurrency]
  type = "requests"
  hard_limit = 500
  soft_limit = 400

[[http_service.checks]]
  grace_period = "2s"
  interval = "2s"
  method = "GET"
  timeout = "2s"
  path = "/live"
