# fly.toml app configuration file generated for differential-core on 2023-08-23T22:01:07+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "differential-core"
primary_region = "lax"

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[http_service.concurrency]
  type = "connections"
  hard_limit = 500
  soft_limit = 400

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "2s"
  path = "/live"