name: Create Release

on: workflow_dispatch

jobs:
  create-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: "0" # fetch all history for all tags and branches so that changeset-builder can generate changelogs

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
          scope: "@differentialhq"

      - name: Install dependencies on root
        run: npm install

      - name: Run tests
        run: npx lerna run test
        env:
          DIFFERENTIAL_API_SECRET: ${{ secrets.DIFFERENTIAL_API_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWKS_URL: ${{ secrets.JWKS_URL }}

      - name: Build packages
        run: npx lerna run build

      - name: Configure Git User
        run: |
          git config --global user.name "Differential CI"
          git config --global user.email "ci@differential.dev"

      - name: Version packages
        run: npx lerna version --conventional-commits --yes --no-private --create-release github
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish packages
        run: npx lerna publish from-package --yes --no-private --registry https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
