name: Run Tests and Generate Changelogs

on:
  push:
    branches:
      - main

jobs:
  default:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0' # fetch all history for all tags and branches so that changeset-builder can generate changelogs

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies on root
        run: npm install

      - name: Run tests
        run: npx lerna run test
        env:
          DIFFERENTIAL_API_SECRET: ${{ secrets.DIFFERENTIAL_API_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Configure Git User
        run: |
          git config --global user.name "Differential CI"
          git config --global user.email "ci@differential.dev"

      - name: Version and publish packages
        run: npx lerna publish --conventional-commits --yes --no-private
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: retypeapp/action-build@latest
        with:
          config: docs

      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true