name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0' # fetch all history for all tags and branches so that changeset-builder can generate changelogs

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: cd ts-core && npm install && cd .. && cd control-plane && npm install && cd ..

      - name: Run tests for ts-core
        run: npm test --prefix ts-core
        env:
          DIFFERENTIAL_API_SECRET: ${{ secrets.DIFFERENTIAL_API_SECRET }}

      - name: Run tests for control-plane
        run: npm test --prefix control-plane
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}